=== YaoLang/geneframework/gene-context/src/main/resources/geneFunction.dtd
<!ELEMENT GeneFunction (define|method)*>
<!ELEMENT define (#PCDATA)>
<!ATTLIST define
          class CDATA #REQUIRED
          method CDATA #REQUIRED
          mark CDATA #REQUIRED>
<!ELEMENT method (#PCDATA)>
<!ATTLIST method
          mark CDATA #IMPLIED
          type CDATA #REQUIRED>

=== YaoLang/geneframework/gene-context/src/main/resources/gene-function.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GeneFunction SYSTEM "src/main/resources/geneFunction.dtd">
<GeneFunction>
		<define class="java.lang.Math" method="sqrt" mark="Q"/>
        <define class="java.lang.Math" method="tan" mark="~"/>
        <method type="abs"/>
        <method type="sin"/>
        <method type="cos"/>
        <method type="log"/>
        <method type="exp"/>
</GeneFunction>
